# Generated by Django 3.2.13 on 2022-04-20 04:41

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='written',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='written_by',
            field=models.ImageField(null=True, upload_to=posts.models.post_image_path),
        ),
    ]
