# Generated by Django 3.2.13 on 2022-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(null=True, upload_to='comments'),
        ),
    ]
