# Generated by Django 3.2.13 on 2022-04-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
